spring:
  application:
    name: utils
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.namejm.utils.dto
  configuration:
    map-underscore-to-camel-case: true
